name: Deploy Nuxt App to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Add SSH Key (if not already present)
      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DROPLET_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      # Step 3: Deploy Docker to DigitalOcean
      - name: Deploy to DigitalOcean
        run: |
          scp -r ./* ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }}:/var/www/nuxt
          ssh ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} "
            cd /var/www/nuxt &&
            docker-compose down &&
            docker-compose up -d --build
          "
