name: Deploy Nuxt App without Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install Dependencies and Build
      - name: Install dependencies and build
        run: |
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt install -y nodejs
          npm ci
          npx nuxt prepare
          npm run build

      # Step 3: Archive Build Folder
      - name: Archive .output folder
        run: tar -czf nuxt-output.tar.gz .output

      # Step 4: Add SSH Key
      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DROPLET_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      # Step 5: Copy Build Archive to Server
      - name: Copy archive to server
        run: scp nuxt-output.tar.gz ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }}:/var/www/nuxt

      # Step 6: Extract Build and Restart App on Server
      - name: Extract and restart app on server
        run: |
          ssh ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} "
            cd /var/www/nuxt &&
            tar -xzf nuxt-output.tar.gz &&
            rm -rf /var/www/nuxt-output &&
            mv .output /var/www/nuxt-output &&
            rm nuxt-output.tar.gz &&
            pm2 describe nuxt > /dev/null && pm2 reload nuxt || pm2 start /var/www/nuxt-output/server/index.mjs --name 'nuxt'
          "
