name: Deploy Nuxt App with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Add SSH Key
      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DROPLET_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      # Step 3: Copy Project to DigitalOcean
      - name: Copy files to server
        run: scp -r ./* ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }}:/var/www/nuxt

      # Step 4: Install Dependencies and Build on Server
      - name: Install dependencies and build
        run: |
         ssh ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} "
           cd /var/www/nuxt &&
           npm install &&
           npx nuxt prepare &&
           npm run generate
         "

      # Step 5: Start or Restart Nuxt App with PM2
      - name: Start or Restart Nuxt App
        run: |
         ssh ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} "
           pm2 describe nuxt > /dev/null && pm2 reload nuxt || pm2 start npm --name 'nuxt' -- start
         "
